application: pensievr
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /cleanup_sessions
  script: cleanup_sessions.py
  login: admin

- url: /(|post|oauth|callback|logout)
  script: pensievr.py
  secure: always

- url: /.*
  static_files: static/error.html
  upload: static/error.html

error_handlers:
- file: static/error.html
